
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jun 20 2026 16:03:11 +0330 (Jun 20 2026 12:33:11 UTC)

// Verification Directory fv/receiver 

module receiver(clk_rx, reset_n, rx_bit, tx_data_valid, rx_data,
     data_valid);
  input clk_rx, reset_n, rx_bit, tx_data_valid;
  output [31:0] rx_data;
  output data_valid;
  wire clk_rx, reset_n, rx_bit, tx_data_valid;
  wire [31:0] rx_data;
  wire data_valid;
  wire [6:0] bit_cnt;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, rx_bit_1st;
  wire rx_bit_2nd, rx_bit_org, tx_data_valid_org, tx_valid_1st,
       tx_valid_2nd;
  DFFRHQX1 \bit_cnt_reg[6] (.RN (reset_n), .CK (clk_rx), .D (n_30), .Q
       (bit_cnt[6]));
  DFFRHQX1 \bit_cnt_reg[5] (.RN (reset_n), .CK (clk_rx), .D (n_27), .Q
       (bit_cnt[5]));
  DFFRHQX1 \bit_cnt_reg[0] (.RN (reset_n), .CK (clk_rx), .D (n_28), .Q
       (bit_cnt[0]));
  OAI21XL g1484__2398(.A0 (n_11), .A1 (tx_data_valid_org), .B0 (n_21),
       .Y (n_30));
  DFFRHQX1 \bit_cnt_reg[3] (.RN (reset_n), .CK (clk_rx), .D (n_24), .Q
       (bit_cnt[3]));
  SDFFRHQX1 \rx_data_reg[19] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[19]), .SI (rx_data[20]), .SE (n_29), .Q (rx_data[19]));
  SDFFRHQX1 \rx_data_reg[5] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[5]), .SI (rx_data[6]), .SE (n_29), .Q (rx_data[5]));
  SDFFRHQX1 \rx_data_reg[6] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[6]), .SI (rx_data[7]), .SE (n_29), .Q (rx_data[6]));
  SDFFRHQX1 \rx_data_reg[3] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[3]), .SI (rx_data[4]), .SE (n_29), .Q (rx_data[3]));
  SDFFRHQX1 \rx_data_reg[7] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[7]), .SI (rx_data[8]), .SE (n_29), .Q (rx_data[7]));
  SDFFRHQX1 \rx_data_reg[8] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[8]), .SI (rx_data[9]), .SE (n_29), .Q (rx_data[8]));
  SDFFRHQX1 \rx_data_reg[10] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[10]), .SI (rx_data[11]), .SE (n_29), .Q (rx_data[10]));
  SDFFRHQX1 \rx_data_reg[2] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[2]), .SI (rx_data[3]), .SE (n_29), .Q (rx_data[2]));
  SDFFRHQX1 \rx_data_reg[12] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[12]), .SI (rx_data[13]), .SE (n_29), .Q (rx_data[12]));
  SDFFRHQX1 \rx_data_reg[13] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[13]), .SI (rx_data[14]), .SE (n_29), .Q (rx_data[13]));
  SDFFRHQX1 \rx_data_reg[14] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[14]), .SI (rx_data[15]), .SE (n_29), .Q (rx_data[14]));
  SDFFRHQX1 \rx_data_reg[15] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[15]), .SI (rx_data[16]), .SE (n_29), .Q (rx_data[15]));
  SDFFRHQX1 \rx_data_reg[11] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[11]), .SI (rx_data[12]), .SE (n_29), .Q (rx_data[11]));
  SDFFRHQX1 \rx_data_reg[16] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[16]), .SI (rx_data[17]), .SE (n_29), .Q (rx_data[16]));
  SDFFRHQX1 \rx_data_reg[17] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[17]), .SI (rx_data[18]), .SE (n_29), .Q (rx_data[17]));
  SDFFRHQX1 \rx_data_reg[18] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[18]), .SI (rx_data[19]), .SE (n_29), .Q (rx_data[18]));
  SDFFRHQX1 \rx_data_reg[0] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[0]), .SI (rx_data[1]), .SE (n_29), .Q (rx_data[0]));
  SDFFRHQX1 \rx_data_reg[20] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[20]), .SI (rx_data[21]), .SE (n_29), .Q (rx_data[20]));
  SDFFRHQX1 \rx_data_reg[21] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[21]), .SI (rx_data[22]), .SE (n_29), .Q (rx_data[21]));
  SDFFRHQX1 \rx_data_reg[22] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[22]), .SI (rx_data[23]), .SE (n_29), .Q (rx_data[22]));
  SDFFRHQX1 \rx_data_reg[9] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[9]), .SI (rx_data[10]), .SE (n_29), .Q (rx_data[9]));
  SDFFRHQX1 \rx_data_reg[24] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[24]), .SI (rx_data[25]), .SE (n_29), .Q (rx_data[24]));
  SDFFRHQX1 \rx_data_reg[25] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[25]), .SI (rx_data[26]), .SE (n_29), .Q (rx_data[25]));
  SDFFRHQX1 \rx_data_reg[26] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[26]), .SI (rx_data[27]), .SE (n_29), .Q (rx_data[26]));
  SDFFRHQX1 \rx_data_reg[27] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[27]), .SI (rx_data[28]), .SE (n_29), .Q (rx_data[27]));
  SDFFRHQX1 \rx_data_reg[28] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[28]), .SI (rx_data[29]), .SE (n_29), .Q (rx_data[28]));
  SDFFRHQX1 \rx_data_reg[1] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[1]), .SI (rx_data[2]), .SE (n_29), .Q (rx_data[1]));
  SDFFRHQX1 \rx_data_reg[23] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[23]), .SI (rx_data[24]), .SE (n_29), .Q (rx_data[23]));
  SDFFRHQX1 \rx_data_reg[30] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[30]), .SI (rx_data[31]), .SE (n_29), .Q (rx_data[30]));
  SDFFRHQX1 \rx_data_reg[31] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[31]), .SI (rx_bit_org), .SE (n_29), .Q (rx_data[31]));
  SDFFRHQX1 \rx_data_reg[29] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[29]), .SI (rx_data[30]), .SE (n_29), .Q (rx_data[29]));
  DFFRHQX1 \bit_cnt_reg[2] (.RN (reset_n), .CK (clk_rx), .D (n_22), .Q
       (bit_cnt[2]));
  SDFFRHQX1 \rx_data_reg[4] (.RN (reset_n), .CK (clk_rx), .D
       (rx_data[4]), .SI (rx_data[5]), .SE (n_29), .Q (rx_data[4]));
  DFFRHQX1 \bit_cnt_reg[4] (.RN (reset_n), .CK (clk_rx), .D (n_26), .Q
       (bit_cnt[4]));
  DFFRHQX1 \bit_cnt_reg[1] (.RN (reset_n), .CK (clk_rx), .D (n_23), .Q
       (bit_cnt[1]));
  OAI21XL g1481__5107(.A0 (n_13), .A1 (tx_data_valid_org), .B0 (n_18),
       .Y (n_28));
  OAI31XL g1473__6260(.A0 (n_20), .A1 (n_25), .A2 (bit_cnt[5]), .B0
       (n_19), .Y (n_27));
  OAI31XL g1479__4319(.A0 (n_5), .A1 (n_25), .A2 (bit_cnt[4]), .B0
       (n_17), .Y (n_26));
  OAI31XL g1477__8428(.A0 (n_7), .A1 (n_25), .A2 (bit_cnt[3]), .B0
       (n_16), .Y (n_24));
  OAI2BB1X1 g1482__5526(.A0N (bit_cnt[1]), .A1N (n_9), .B0 (n_14), .Y
       (n_23));
  OAI31XL g1483__6783(.A0 (n_25), .A1 (n_3), .A2 (bit_cnt[2]), .B0
       (n_15), .Y (n_22));
  NAND3BX1 g1490__3680(.AN (n_20), .B (n_10), .C (bit_cnt[5]), .Y
       (n_21));
  NAND2X1 g1478__1617(.A (n_12), .B (bit_cnt[5]), .Y (n_19));
  INVXL g1485(.A (n_29), .Y (n_18));
  NAND2X1 g1486__2802(.A (n_6), .B (bit_cnt[4]), .Y (n_17));
  NAND2X1 g1487__1705(.A (n_8), .B (bit_cnt[3]), .Y (n_16));
  NOR2X1 g1489__5122(.A (n_25), .B (bit_cnt[0]), .Y (n_29));
  NAND2X1 g1492__8246(.A (n_4), .B (bit_cnt[2]), .Y (n_15));
  OR3XL g1493__7098(.A (n_25), .B (n_13), .C (bit_cnt[1]), .Y (n_14));
  SDFFRHQX1 data_valid_reg(.RN (reset_n), .CK (clk_rx), .D
       (data_valid), .SI (bit_cnt[6]), .SE (tx_data_valid_org), .Q
       (data_valid));
  DFFRHQX1 rx_bit_org_reg(.RN (reset_n), .CK (clk_rx), .D (n_2), .Q
       (rx_bit_org));
  OAI2BB1X1 g1491__6131(.A0N (n_11), .A1N (n_20), .B0
       (tx_data_valid_org), .Y (n_12));
  INVX1 g1494(.A (n_25), .Y (n_10));
  OAI21XL g1495__1881(.A0 (bit_cnt[0]), .A1 (bit_cnt[6]), .B0
       (tx_data_valid_org), .Y (n_9));
  OAI2BB1X1 g1496__5115(.A0N (n_11), .A1N (n_7), .B0
       (tx_data_valid_org), .Y (n_8));
  OAI2BB1X1 g1499__7482(.A0N (n_11), .A1N (n_5), .B0
       (tx_data_valid_org), .Y (n_6));
  OAI2BB1X1 g1500__4733(.A0N (n_11), .A1N (n_3), .B0
       (tx_data_valid_org), .Y (n_4));
  NAND2X1 g1497__6161(.A (n_11), .B (tx_data_valid_org), .Y (n_25));
  OAI2BB1X1 g1498__9315(.A0N (rx_bit_2nd), .A1N (rx_bit_1st), .B0
       (n_1), .Y (n_2));
  DFFRHQX1 tx_data_valid_org_reg(.RN (reset_n), .CK (clk_rx), .D (n_0),
       .Q (tx_data_valid_org));
  NAND2BX1 g1503__9945(.AN (n_5), .B (bit_cnt[4]), .Y (n_20));
  OAI21XL g1502__2883(.A0 (rx_bit_2nd), .A1 (rx_bit_1st), .B0
       (rx_bit_org), .Y (n_1));
  NAND2BX1 g1504__2346(.AN (n_7), .B (bit_cnt[3]), .Y (n_5));
  AND2X2 g1505__1666(.A (tx_valid_1st), .B (tx_valid_2nd), .Y (n_0));
  DFFRHQX1 tx_valid_2nd_reg(.RN (reset_n), .CK (clk_rx), .D
       (tx_valid_1st), .Q (tx_valid_2nd));
  DFFRHQX1 rx_bit_2nd_reg(.RN (reset_n), .CK (clk_rx), .D (rx_bit_1st),
       .Q (rx_bit_2nd));
  NAND2BX1 g1508__7410(.AN (n_3), .B (bit_cnt[2]), .Y (n_7));
  DFFRHQX1 tx_valid_1st_reg(.RN (reset_n), .CK (clk_rx), .D
       (tx_data_valid), .Q (tx_valid_1st));
  NAND2X1 g1511__6417(.A (bit_cnt[0]), .B (bit_cnt[1]), .Y (n_3));
  DFFRHQX1 rx_bit_1st_reg(.RN (reset_n), .CK (clk_rx), .D (rx_bit), .Q
       (rx_bit_1st));
  INVX1 g1512(.A (bit_cnt[6]), .Y (n_11));
  INVX1 g1513(.A (bit_cnt[0]), .Y (n_13));
endmodule

