
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jun 20 2026 11:26:36 +0330 (Jun 20 2026 07:56:36 UTC)

// Verification Directory fv/synchronizer 


`timescale 1ps/1fs

module synchronizer(clk, reset_n, async_in, sync_out);
  input clk, reset_n, async_in;
  output sync_out;
  wire clk, reset_n, async_in;
  wire sync_out;
  wire sync_ff1;

  reg sync_out_resolved;
  reg resolving =1'b0;
  
  DFFRHQX1 sync_ff1_reg(.RN (reset_n), .CK (clk), .D (async_in), .Q
       (sync_ff1));

  DFFRHQXL sync_ff2_reg(.RN (reset_n), .CK (clk), .D (sync_out_resolved), .Q
       (sync_out));
       

       always @(sync_ff1) begin
          if (sync_ff1==1'b1)
              sync_out_resolved = 1'b1;
          else if (sync_ff1==1'b0)
              sync_out_resolved = 1'b0;
          else if (sync_ff1==1'bx) begin
              #100;
              sync_out_resolved = $urandom_range(0,1);
          end
       end
       /*
       always @(sync_ff1) begin
       casex (sync_ff1)
           1'bx           : 
              if (!resolving) begin
                 resolving = 1;
                 #100;
                 sync_out_resolved = $urandom_range(0,1);
                 resolving = 0;
              end
           1'b1           : sync_out_resolved = 1'b1;
           1'b0           : sync_out_resolved = 1'b0;
           default        : sync_out_resolved = 1'b0;
       endcase
    end
     */
endmodule

