
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jun 20 2026 16:03:06 +0330 (Jun 20 2026 12:33:06 UTC)

// Verification Directory fv/transmitter 

module transmitter(clk_tx, reset_n, tx_bit, tx_data_valid);
  input clk_tx, reset_n;
  output tx_bit, tx_data_valid;
  wire clk_tx, reset_n;
  wire tx_bit, tx_data_valid;
  wire [31:0] tx_out_reg;
  wire [5:0] bit_cnt;
  wire load, n_0, n_1, n_2, n_3, n_6, n_7, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_56, n_57;
  SDFFHQX1 tx_bit_reg(.CK (clk_tx), .D (tx_out_reg[0]), .SI (tx_bit),
       .SE (n_2), .Q (tx_bit));
  DFFRHQXL \tx_out_reg_reg[0] (.RN (reset_n), .CK (clk_tx), .D (n_57),
       .Q (tx_out_reg[0]));
  NOR2BXL g347__2398(.AN (tx_out_reg[1]), .B (n_12), .Y (n_57));
  DFFRHQXL \tx_out_reg_reg[1] (.RN (reset_n), .CK (clk_tx), .D (n_56),
       .Q (tx_out_reg[1]));
  NOR2BXL g349__5107(.AN (tx_out_reg[2]), .B (n_12), .Y (n_56));
  DFFRHQXL \tx_out_reg_reg[2] (.RN (reset_n), .CK (clk_tx), .D (n_54),
       .Q (tx_out_reg[2]));
  NOR2BXL g351__6260(.AN (tx_out_reg[3]), .B (n_12), .Y (n_54));
  DFFRHQXL \tx_out_reg_reg[3] (.RN (reset_n), .CK (clk_tx), .D (n_53),
       .Q (tx_out_reg[3]));
  NOR2BXL g353__4319(.AN (tx_out_reg[4]), .B (n_12), .Y (n_53));
  DFFRHQXL \tx_out_reg_reg[4] (.RN (reset_n), .CK (clk_tx), .D (n_52),
       .Q (tx_out_reg[4]));
  OR2X2 g355__8428(.A (n_12), .B (tx_out_reg[5]), .Y (n_52));
  DFFRHQXL \tx_out_reg_reg[5] (.RN (reset_n), .CK (clk_tx), .D (n_51),
       .Q (tx_out_reg[5]));
  OR2X2 g357__5526(.A (n_12), .B (tx_out_reg[6]), .Y (n_51));
  DFFRHQXL \tx_out_reg_reg[6] (.RN (reset_n), .CK (clk_tx), .D (n_50),
       .Q (tx_out_reg[6]));
  OR2X2 g359__6783(.A (n_12), .B (tx_out_reg[7]), .Y (n_50));
  DFFRHQXL \tx_out_reg_reg[7] (.RN (reset_n), .CK (clk_tx), .D (n_49),
       .Q (tx_out_reg[7]));
  OR2X2 g361__3680(.A (n_12), .B (tx_out_reg[8]), .Y (n_49));
  DFFRHQXL \tx_out_reg_reg[8] (.RN (reset_n), .CK (clk_tx), .D (n_48),
       .Q (tx_out_reg[8]));
  NOR2BXL g363__1617(.AN (tx_out_reg[9]), .B (n_12), .Y (n_48));
  DFFRHQXL \tx_out_reg_reg[9] (.RN (reset_n), .CK (clk_tx), .D (n_47),
       .Q (tx_out_reg[9]));
  NOR2BXL g365__2802(.AN (tx_out_reg[10]), .B (n_12), .Y (n_47));
  DFFRHQXL \tx_out_reg_reg[10] (.RN (reset_n), .CK (clk_tx), .D (n_46),
       .Q (tx_out_reg[10]));
  NOR2BXL g367__1705(.AN (tx_out_reg[11]), .B (n_12), .Y (n_46));
  DFFRHQXL \tx_out_reg_reg[11] (.RN (reset_n), .CK (clk_tx), .D (n_45),
       .Q (tx_out_reg[11]));
  NOR2BXL g369__5122(.AN (tx_out_reg[12]), .B (n_12), .Y (n_45));
  DFFRHQXL \tx_out_reg_reg[12] (.RN (reset_n), .CK (clk_tx), .D (n_44),
       .Q (tx_out_reg[12]));
  OR2X2 g371__8246(.A (n_12), .B (tx_out_reg[13]), .Y (n_44));
  DFFRHQXL \tx_out_reg_reg[13] (.RN (reset_n), .CK (clk_tx), .D (n_43),
       .Q (tx_out_reg[13]));
  OR2X2 g373__7098(.A (n_12), .B (tx_out_reg[14]), .Y (n_43));
  DFFRHQXL \tx_out_reg_reg[14] (.RN (reset_n), .CK (clk_tx), .D (n_42),
       .Q (tx_out_reg[14]));
  OR2X2 g375__6131(.A (n_12), .B (tx_out_reg[15]), .Y (n_42));
  DFFRHQXL \tx_out_reg_reg[15] (.RN (reset_n), .CK (clk_tx), .D (n_41),
       .Q (tx_out_reg[15]));
  OR2X2 g377__1881(.A (n_12), .B (tx_out_reg[16]), .Y (n_41));
  DFFRHQXL \tx_out_reg_reg[16] (.RN (reset_n), .CK (clk_tx), .D (n_40),
       .Q (tx_out_reg[16]));
  NOR2BXL g379__5115(.AN (tx_out_reg[17]), .B (n_12), .Y (n_40));
  DFFRHQXL \tx_out_reg_reg[17] (.RN (reset_n), .CK (clk_tx), .D (n_39),
       .Q (tx_out_reg[17]));
  NOR2BXL g381__7482(.AN (tx_out_reg[18]), .B (n_12), .Y (n_39));
  DFFRHQXL \tx_out_reg_reg[18] (.RN (reset_n), .CK (clk_tx), .D (n_38),
       .Q (tx_out_reg[18]));
  NOR2BXL g383__4733(.AN (tx_out_reg[19]), .B (n_12), .Y (n_38));
  DFFRHQXL \tx_out_reg_reg[19] (.RN (reset_n), .CK (clk_tx), .D (n_37),
       .Q (tx_out_reg[19]));
  NOR2BXL g385__6161(.AN (tx_out_reg[20]), .B (n_12), .Y (n_37));
  DFFRHQXL \tx_out_reg_reg[20] (.RN (reset_n), .CK (clk_tx), .D (n_36),
       .Q (tx_out_reg[20]));
  OR2X2 g387__9315(.A (n_12), .B (tx_out_reg[21]), .Y (n_36));
  DFFRHQXL \tx_out_reg_reg[21] (.RN (reset_n), .CK (clk_tx), .D (n_35),
       .Q (tx_out_reg[21]));
  OR2X2 g389__9945(.A (n_12), .B (tx_out_reg[22]), .Y (n_35));
  DFFRHQXL \tx_out_reg_reg[22] (.RN (reset_n), .CK (clk_tx), .D (n_34),
       .Q (tx_out_reg[22]));
  OR2X2 g391__2883(.A (n_12), .B (tx_out_reg[23]), .Y (n_34));
  DFFRHQXL \tx_out_reg_reg[23] (.RN (reset_n), .CK (clk_tx), .D (n_33),
       .Q (tx_out_reg[23]));
  OR2X2 g393__2346(.A (n_12), .B (tx_out_reg[24]), .Y (n_33));
  DFFRHQXL \tx_out_reg_reg[24] (.RN (reset_n), .CK (clk_tx), .D (n_32),
       .Q (tx_out_reg[24]));
  NOR2BXL g395__1666(.AN (tx_out_reg[25]), .B (n_12), .Y (n_32));
  DFFRHQXL \tx_out_reg_reg[25] (.RN (reset_n), .CK (clk_tx), .D (n_31),
       .Q (tx_out_reg[25]));
  NOR2BXL g397__7410(.AN (tx_out_reg[26]), .B (n_12), .Y (n_31));
  DFFRHQXL \tx_out_reg_reg[26] (.RN (reset_n), .CK (clk_tx), .D (n_30),
       .Q (tx_out_reg[26]));
  NOR2BXL g399__6417(.AN (tx_out_reg[27]), .B (n_12), .Y (n_30));
  DFFRHQXL \tx_out_reg_reg[27] (.RN (reset_n), .CK (clk_tx), .D (n_29),
       .Q (tx_out_reg[27]));
  NOR2BXL g401__5477(.AN (tx_out_reg[28]), .B (n_12), .Y (n_29));
  DFFRHQXL \tx_out_reg_reg[28] (.RN (reset_n), .CK (clk_tx), .D (n_28),
       .Q (tx_out_reg[28]));
  OR2X2 g404__2398(.A (n_12), .B (tx_out_reg[29]), .Y (n_28));
  DFFRHQXL \tx_out_reg_reg[29] (.RN (reset_n), .CK (clk_tx), .D (n_27),
       .Q (tx_out_reg[29]));
  DFFRHQX1 \bit_cnt_reg[4] (.RN (reset_n), .CK (clk_tx), .D (n_26), .Q
       (bit_cnt[4]));
  OR2X2 g409__5107(.A (n_12), .B (tx_out_reg[30]), .Y (n_27));
  DFFRHQX1 \bit_cnt_reg[3] (.RN (reset_n), .CK (clk_tx), .D (n_25), .Q
       (bit_cnt[3]));
  OAI32XL g408__6260(.A0 (n_22), .A1 (n_24), .A2 (bit_cnt[4]), .B0
       (n_19), .B1 (n_21), .Y (n_26));
  OAI31XL g411__4319(.A0 (n_24), .A1 (n_13), .A2 (bit_cnt[3]), .B0
       (n_20), .Y (n_25));
  DFFRHQXL \tx_out_reg_reg[30] (.RN (reset_n), .CK (clk_tx), .D (n_17),
       .Q (tx_out_reg[30]));
  DFFRHQX1 \bit_cnt_reg[5] (.RN (reset_n), .CK (clk_tx), .D (n_23), .Q
       (bit_cnt[5]));
  DFFRHQX1 \bit_cnt_reg[2] (.RN (reset_n), .CK (clk_tx), .D (n_16), .Q
       (bit_cnt[2]));
  OAI32X1 g412__8428(.A0 (n_22), .A1 (n_24), .A2 (n_21), .B0 (load),
       .B1 (n_18), .Y (n_23));
  DFFRHQX1 \bit_cnt_reg[1] (.RN (reset_n), .CK (clk_tx), .D (n_15), .Q
       (bit_cnt[1]));
  OAI21XL g415__5526(.A0 (n_14), .A1 (n_12), .B0 (bit_cnt[3]), .Y
       (n_20));
  AOI21X1 g417__6783(.A0 (n_22), .A1 (n_18), .B0 (n_12), .Y (n_19));
  NAND2BX1 g419__3680(.AN (tx_out_reg[31]), .B (load), .Y (n_17));
  SDFFRHQX1 \bit_cnt_reg[0] (.RN (reset_n), .CK (clk_tx), .D (n_7), .SI
       (n_12), .SE (bit_cnt[0]), .Q (bit_cnt[0]));
  OAI32X1 g416__1617(.A0 (n_24), .A1 (n_9), .A2 (bit_cnt[2]), .B0
       (n_10), .B1 (n_0), .Y (n_16));
  OAI31XL g420__2802(.A0 (n_24), .A1 (n_1), .A2 (bit_cnt[1]), .B0
       (n_11), .Y (n_15));
  DFFRHQXL \tx_out_reg_reg[31] (.RN (reset_n), .CK (clk_tx), .D (n_12),
       .Q (tx_out_reg[31]));
  DFFRHQXL tx_data_valid_reg(.RN (reset_n), .CK (clk_tx), .D (load), .Q
       (tx_data_valid));
  AND2X2 g424__1705(.A (n_13), .B (n_18), .Y (n_14));
  NAND2BX1 g426__5122(.AN (n_13), .B (bit_cnt[3]), .Y (n_22));
  DFFRX1 load_reg(.RN (reset_n), .CK (clk_tx), .D (n_6), .Q (n_12), .QN
       (load));
  OAI21XL g423__8246(.A0 (n_3), .A1 (n_12), .B0 (bit_cnt[1]), .Y
       (n_11));
  AOI21X1 g425__7098(.A0 (n_9), .A1 (n_18), .B0 (n_12), .Y (n_10));
  INVXL g431(.A (n_24), .Y (n_7));
  NAND2BX1 g427__6131(.AN (n_9), .B (bit_cnt[2]), .Y (n_13));
  NOR2XL g436__1881(.A (n_18), .B (n_12), .Y (n_6));
  NAND2X1 g434__5115(.A (n_18), .B (load), .Y (n_24));
  NAND2X1 g433__7482(.A (bit_cnt[0]), .B (bit_cnt[1]), .Y (n_9));
  NOR2XL g432__4733(.A (bit_cnt[5]), .B (bit_cnt[0]), .Y (n_3));
  NAND2X1 g437__6161(.A (load), .B (reset_n), .Y (n_2));
  INVX1 g441(.A (bit_cnt[0]), .Y (n_1));
  INVX1 g439(.A (bit_cnt[2]), .Y (n_0));
  INVX1 g440(.A (bit_cnt[4]), .Y (n_21));
  INVX1 g443(.A (bit_cnt[5]), .Y (n_18));
endmodule

